### ISSUE TITLE
Create SQL Query for inserting Events

### ISSUE THREAD

**Issue by ghost** [TeamSyed/EventWebApp#12]
User Story #1
Complete on  Feb 26, 2015: 288a0537fee42ac767e890ba5ec84e5e528f5271

**Comment by ghost** [comment]
Hey Agnisen, this isn't completely done and you can't really finish it properly until the database is done. Also It would use variables of the Add Events form, not actual values. See for info http://www.tutorialspoint.com/php/mysql_insert_php.htm

**Comment by agnisen79** [comment]
Yes I left a comment for the query of adding events , I didn't mention the actual values in the comment

**Comment by ghost** [comment]
Task was being worked on by Agnisen, but was completed by Rahul in order to complete his other  task of submitting to the database.
