### ISSUE TITLE
Code the UI for search which will appear on each page

### ISSUE THREAD

**Issue by ghost** [TeamSyed/EventWebApp#17]
User Story #2
Completed on Feb 19, 2015: cd438754c1925ceae7335da0c9e5d27ea712745a

**Comment by rohit071** [comment]
Added search that appears on each page.

**Comment by ghost** [comment]
Advanced search GUI isn't implemented so reopening.

**Comment by rohit071** [comment]
Please let me know if there is any other option that can be implemented. Added advanced search GUI.

**Comment by ghost** [comment]
That looks good, you don't need title and location in advanced search, so remove title and location as basic search will do that, Where it says 'Search Here' you can say Search Event Titles, Location, Description

And Advanced Search remove title and location and make the following changes to data and time, and that should be everything

Date: 
From: { Input } To: {Input}
Time: From: {Input} To: {Input}

**Comment by rohit071** [comment]
Done as you said. Please take another look.

**Comment by rohit071** [comment]
I did not remove title because i think that will be a good option to search by title.

**Comment by ghost** [comment]
Alright checked it out, I'm good with the changes.
