### ISSUE TITLE
Code advanced search on page

### ISSUE THREAD

**Issue by ghost** [TeamSyed/EventWebApp#18]

**Comment by ghost** [comment]
User Story #2

**Comment by rohit071** [comment]
Waiting on advanced search query.

**Comment by rohit071** [comment]
Added Advanced Search. Errors in query.

**Comment by natejhmai** [comment]
Please provide me how long it took you to complete

**Comment by natejhmai** [comment]
@rohit071 Please provide me how long it took you to complete

**Comment by rohit071** [comment]
2.5
