### ISSUE TITLE
Create the UI for search results page

### ISSUE THREAD

**Issue by ghost** [TeamSyed/EventWebApp#45]
User Story #6
Complete on  Feb 20, 2015 : 7066cedfc5dd14aa4b7216dabcb5e125b5303739

**Comment by rohit071** [comment]
Task Completed. Let me know if you have any concerns.

**Comment by ghost** [comment]
I'm fine with it, but did you make a template for whats in div class=middle> because when you search it would repeat the search results in that format, and the description, title placeholder would be replaced with the query results. Store the template in Resources/templates

**Comment by rohit071** [comment]
yes.. its just the template. all results will be replaced by actal data with queries.
