### ISSUE TITLE
Code to get directions from start and destination using Google API

### ISSUE THREAD

**Issue by ghost** [TeamSyed/EventWebApp#86]
User Story #55

**Comment by rohit071** [comment]
Started task.

**Comment by rohit071** [comment]
Task COmpleted
d1e2690fb49d66e4cdd941319e2d4c9b6dd36cba Final Commit for the task.
Took three hours to complete. Was more work that expected.
The work included geocoding that is converting address to latitude and longitude  plus sign up on google api to get API Key.
